// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    dest: './build',
    layer: {
      app: {
        src: './app',
        glob: '**/*.js'
      }
    },
    bundle: {
      app: {
        target: 'browser-full',
        props: {
          argv: ['/app/index.js'],
          env: {
            PWD: '/app'
          },
          modules: []
        },
        volumes: [['/app', 'app']]
      }
    }
  };

}).call(this);
