// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    dest: './build',
    layers: {
      lib: {
        base: './lib',
        globs: ['**/*.js'],
        minify: false,
        dest: './dist'
      },
      libmin: {
        base: './libmin',
        globs: ['**/*.js'],
        minify: false,
        dest: './dist'
      },
      clisrc: {
        base: './src',
        globs: ['**/*.js'],
        minify: false
      },
      clinode: {
        base: './node_modules',
        globs: ['!(cli)/**/*.+(js|json)', 'cli/*.+(js|json)', 'cli/!(examples)/**/*.+(js|json)'],
        minify: false
      },
      example: {
        format: 'json',
        base: './example',
        dest: './example',
        filename: 'volume.json',
        globs: ['**/*.js'],
        minify: false
      }
    },
    merge: {
      cli: {
        layers: [['', 'clinode'], ['node_modules', 'clisrc']]
      }
    },
    "package": {
      cli: {
        type: 'node',
        volumes: [['/app', 'cli']]
      },
      example: {
        dest: './example/app.js',
        type: 'browser',
        lib: 'libmin',
        argv: ['/app/example.js'],
        env: {
          PWD: '/app'
        },
        volumes: [['/app', 'example']]
      }
    }
  };

}).call(this);
