// Generated by CoffeeScript 1.8.0
(function() {
  var minify;

  minify = function(file) {
    var uglify;
    uglify = require('uglify-js');
    file.raw = uglify.minify(file.raw, {
      fromString: true
    }).code;
    if (file.filepath.match('portable\.js')) {
      return file.raw = "(function(process){" + file.raw + "})";
    }
  };

  module.exports = {
    dest: './build',
    layer: {
      lib: {
        src: './lib',
        glob: '**/*.js',
        transform: ['.+\.js$', minify]
      },
      libmini: {
        src: './libmini',
        glob: '**/*.js',
        transform: ['.+\.js$', minify]
      },
      libmicro: {
        src: './libmicro',
        glob: '**/*.js',
        transform: ['.+\.js$', minify]
      },
      clisrc: {
        src: './src',
        glob: '**/*.js',
        transform: ['.+\.js$', 'uglify']
      },
      clinode: {
        src: './node_modules',
        glob: ['!(cli)/**/*.+(js|json)', 'cli/*.+(js|json)', 'cli/!(examples)/**/*.+(js|json)']
      }
    },
    merge: {
      cli: {
        layers: [['clisrc', 'src'], ['clinode', 'node_modules']]
      }
    },
    bundle: {
      cli: {
        target: 'node',
        volumes: [['/portable', 'cli']],
        props: {
          main: '/portable/src/cli.js'
        }
      }
    },
    server: {
      port: 1777
    }
  };

}).call(this);
